services:
  raylib-dev:
    build: .
    working_dir: /app
    volumes:
      - ./src:/app/src
    stdin_open: true
    tty: true
    command: bash

  raylib-dev-windows:
    container_name: factorygame-dev-windows
    extends:
      service: raylib-dev
    environment:
      DISPLAY: host.docker.internal:0
    profiles: ["windows"]

  raylib-dev-linux:
    container_name: factorygame-dev-linux
    extends:
      service: raylib-dev
    environment:
      DISPLAY: ${DISPLAY}
      WAYLAND_DISPLAY: ${WAYLAND_DISPLAY}
      XDG_RUNTIME_DIR: ${XDG_RUNTIME_DIR}
    volumes:
      - ./src:/app/src
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri:/dev/dri
    profiles: ["linux"]
